... => …
mannynotfound/manny pull request #1
Opened 2016-09-24 00:08 UTC by rolyatmax

just wanted to contribute…

2016-09-24 00:24 UTC, mannynotfound requested changes
This is a good start but why stop here? For consistency, I think we should strictly use unicode spaces. More on that [here](https://www.smashingmagazine.com/2015/10/space-yourself/#meet-the-spaces)

2016-09-24 00:35 UTC, rolyatmax commented
Sounds like a weekend project. I'll create some Jira tickets.

2016-11-24 16:34 UTC, mannynotfound approved these changes

2016-11-24 16:35 UTC, mannynotfound commented
gunna merge this for now but lets get some tickets up for the outstanding tasks

2016-11-24 16:35 UTC, merged